language: python
python:
  - "2.7"
  - "3.3"

script: python setup.py test

notifications:
  irc:
    channels: "irc.psas.pdx.edu#psas"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false
